# :stopdoc:
################################################################
################################################################
##   ________  ________  ________  ________  ___  ___  ________ _________        _____ ______   _______   ________  ___  ________     
##  |\   __  \|\   __  \|\   __  \|\   ___ \|\  \|\  \|\   ____\\___   ___\     |\   _ \  _   \|\  ___ \ |\   ___ \|\  \|\   __  \    
##  \ \  \|\  \ \  \|\  \ \  \|\  \ \  \_|\ \ \  \\\  \ \  \___\|___ \  \_|     \ \  \\\__\ \  \ \   __/|\ \  \_|\ \ \  \ \  \|\  \   
##   \ \   ____\ \   _  _\ \  \\\  \ \  \ \\ \ \  \\\  \ \  \       \ \  \       \ \  \\|__| \  \ \  \_|/_\ \  \ \\ \ \  \ \   __  \  
##    \ \  \___|\ \  \\  \\ \  \\\  \ \  \_\\ \ \  \\\  \ \  \____   \ \  \       \ \  \    \ \  \ \  \_|\ \ \  \_\\ \ \  \ \  \ \  \ 
##     \ \__\    \ \__\\ _\\ \_______\ \_______\ \_______\ \_______\  \ \__\       \ \__\    \ \__\ \_______\ \_______\ \__\ \__\ \__\
##      \|__|     \|__|\|__|\|_______|\|_______|\|_______|\|_______|   \|__|        \|__|     \|__|\|_______|\|_______|\|__|\|__|\|__|
##  --
##  RPECK 23/04/2026 - WEbhook
##  Provides the means to interface with the Shopify webhooks system
################################################################
################################################################
# :startdoc:

# = Shopify Namespace
#
# Provides isolated domain grouping to manage exactly how various external
# e-commerce platform data models are mapped internally.
module Shopify 

  # = Shopify Product Media Object
  #
  # Offloads and tracks rich media components (including static images, streaming 
  # videos, and interactive 3D models) synchronized via webhook streams 
  # and GraphQL Admin API interfaces.
  #
  # == Database Schema Attributes
  #
  # [id]          Autogenerated primary platform tracking identifier.
  # [shop_id]     Foreign key reference routing to the managing +Shop+ model.
  # [shopify_id]  The immutable canonical Global Identifier (+GID+) passed from Shopify.
  # [url]         The structural fallback source web layout or asset CDN address.
  # [height]      The pixel vertical coordinate sizing boundary, if applicable.
  # [width]       The pixel horizontal coordinate sizing boundary, if applicable.
  # [alt]         Alternative text accessibility tags utilized by screen readers and SEO crawlers.
  # [media_type]  Explicit data format discriminator (e.g., <tt>"image"</tt>, <tt>"video"</tt>, <tt>"model"</tt>).
  # [meta]        Schema-less JSON tracking parameters dedicated to ongoing asset customization hooks.
  # [created_at]  System timestamp marking initial database resource allocation.
  # [updated_at]  System timestamp tracking the most recent synchronization event mutation.
  #
  # == Core Model Lifecycle Associations
  #
  # * Every discrete media asset strictly belongs to an underlying multi-tenant +Shop+ resource.
  # * Media records maintain an active, un-scoped join network with multiple structural +Products+.
  class ProductMedia < ApplicationRecord

    # == Model Relationships
    
    # Each media payload is contextually dependent on a single parent storefront.
    belongs_to :shop, inverse_of: :product_media, required: true 

    # Unifies independent asset links across several internal product configurations.
    has_and_belongs_to_many :products

    # == Query Search Scopes
    
    # Isolate traditional 2D graphical image rows.
    scope :images, -> { where(media_type: 'image') }
    
    # Filter incoming dynamic playback configurations or external stream URLs.
    scope :videos, -> { where(media_type: 'video') }
    
    # Isolate immersive augmented reality (+AR+) or spatial product configurations.
    scope :models, -> { where(media_type: 'model') }

  end

end