# :stopdoc:
################################################################
################################################################
##   ________  ________  ________  ________  ___  ___  ________ _________        _____ ______   _______   ________  ___  ________     
##  |\   __  \|\   __  \|\   __  \|\   ___ \|\  \|\  \|\   ____\\___   ___\     |\   _ \  _   \|\  ___ \ |\   ___ \|\  \|\   __  \    
##  \ \  \|\  \ \  \|\  \ \  \|\  \ \  \_|\ \ \  \\\  \ \  \___\|___ \  \_|     \ \  \\\__\ \  \ \   __/|\ \  \_|\ \ \  \ \  \|\  \   
##   \ \   ____\ \   _  _\ \  \\\  \ \  \ \\ \ \  \\\  \ \  \       \ \  \       \ \  \\|__| \  \ \  \_|/_\ \  \ \\ \ \  \ \   __  \  
##    \ \  \___|\ \  \\  \\ \  \\\  \ \  \_\\ \ \  \\\  \ \  \____   \ \  \       \ \  \    \ \  \ \  \_|\ \ \  \_\\ \ \  \ \  \ \  \ 
##     \ \__\    \ \__\\ _\\ \_______\ \_______\ \_______\ \_______\  \ \__\       \ \__\    \ \__\ \_______\ \_______\ \__\ \__\ \__\
##      \|__|     \|__|\|__|\|_______|\|_______|\|_______|\|_______|   \|__|        \|__|     \|__|\|_______|\|_______|\|__|\|__|\|__|
##  --
##  RPECK 23/04/2026 - Product Media
##  Model which provides the means to store product media inside the database
##  --
##  Ref: 
################################################################
################################################################
# :startdoc:

# frozen_string_literal: true

module XEngine
  module Shopify
    # = Shopify Product Media Model
    #
    # Offloads and tracks rich media components (including static images, streaming 
    # videos, and interactive 3D models) synchronized via webhook streams 
    # and GraphQL Admin API interfaces.
    #
    # == Database Schema Attributes
    #
    # [id]          Autogenerated primary platform tracking identifier.
    # [shop_id]     Foreign key reference routing to the managing +Shop+ model.
    # [shopify_id]  The immutable canonical Global Identifier (+GID+) passed from Shopify.
    # [url]         The structural fallback source web layout or asset CDN address.
    # [height]      The pixel vertical coordinate sizing boundary, if applicable.
    # [width]       The pixel horizontal coordinate sizing boundary, if applicable.
    # [alt]         Alternative text accessibility tags utilized by screen readers and SEO crawlers.
    # [media_type]  Explicit data format discriminator (e.g., <tt>"image"</tt>, <tt>"video"</tt>, <tt>"model"</tt>).
    # [meta]        Schema-less JSON tracking parameters dedicated to ongoing asset customization hooks.
    # [created_at]  System timestamp marking initial database resource allocation.
    # [updated_at]  System timestamp tracking the most recent synchronization event mutation.
    #
    # == Lifecycle Integration
    # This resource states its unified sub-selection GraphQL API payload configuration natively 
    # via the {XEngine::Shopify::HasGraphQLRepresentation} concern. Because media connections are strictly 
    # dependent children inside Shopify's graph schema, it does not define standalone root endpoints.
    #
    class ProductMedia < XEngine::Core::Model
      include XEngine::Shopify::HasGraphQLRepresentation

      # == GraphQL Layout Declarations
      # Exposed strictly as a child query fragment template component. 
      # Handles images, native videos, external embeds, and spatial 3D model assets natively.
      expose_graphql do
        <<~GRAPHQL
          __typename
          id
          
          # 1. Standard 2D Graphical Images
          ... on MediaImage {
            image {
              url
              height
              width
            }
          }
          
          # 2. Native MP4/HLS Uploaded Videos
          ... on Video {
            duration
            originalSource {
              url
              mimeType
              height
              width
            }
          }
          
          # 3. Embedded YouTube / Vimeo Streams
          ... on ExternalVideo {
            embeddedUrl
            host
          }
          
          # 4. Immersive Spatial / AR 3D Models
          ... on Model3d {
            alt
            originalSource {
              url
              filesize
            }
          }
        GRAPHQL
      end

      # == Associations
      belongs_to :shop, class_name: "XEngine::Shopify::Shop", inverse_of: :product_media

      has_and_belongs_to_many :products, -> { distinct }, class_name: "XEngine::Shopify::Product"

      # == Scopes
      
      # Isolate traditional 2D graphical image rows.
      scope :images, -> { where(media_type: "image") }
      
      # Filter incoming dynamic playback configurations or external stream URLs.
      scope :videos, -> { where(media_type: "video") }
      
      # Isolate immersive augmented reality (+AR+) or spatial product configurations.
      scope :models, -> { where(media_type: "model") }
    end

    # = Shopify Media Image Subclass
    # Concrete STI model for static 2D image assets (+MediaImage+).
    class MediaImage < ProductMedia
    end

    # = Shopify Video Subclass
    # Concrete STI model for Shopify-hosted native video files (+Video+).
    class Video < ProductMedia
    end

    # = Shopify External Video Subclass
    # Concrete STI model for embedded external video links (+ExternalVideo+ e.g., YouTube/Vimeo).
    class ExternalVideo < ProductMedia
    end

    # = Shopify 3D Model Subclass
    # Concrete STI model for spatial AR/3D object assets (+Model3d+).
    class Model3d < ProductMedia
    end

  end
end