# :stopdoc:
################################################################
################################################################
##  ________  ___  ___  ___       ___  __              ________  ________  _______   ________  ________  _________  ___  ________  ________      
## |\   __  \|\  \|\  \|\  \     |\  \|\  \           |\   __  \|\   __  \|\  ___ \ |\   __  \|\   __  \|\___   ___\\  \|\   __  \|\   ___  \    
## \ \  \|\ /\ \  \\\  \ \  \    \ \  \/  /|_         \ \  \|\  \ \  \|\  \ \  \__ /|\ \  \|\ \ \  \|\  \|___ \  \_\ \  \ \  \|\  \ \  \\ \  \   
##  \ \   __  \ \  \\\  \ \  \    \ \   ___  \         \ \  \\\  \ \   ____\ \  \_|/_\ \  _  __\ \  .__  \   \ \  \ \ \  \ \  \\\  \ \  \\ \  \  
##   \ \  \|\  \ \  \\\  \ \  \____\ \  \\ \  \         \ \  \\\  \ \  \___|\ \  \_|\ \ \  \\  \\ \  \ \  \   \ \  \ \ \  \ \  \\\  \ \  \\ \  \ 
##    \ \_______\ \_______\ \_______\ \__\\ \__\         \ \_______\ \__\    \ \_______\ \__\\ _\\ \__\ \__\   \ \__\ \ \__\ \_______\ \__\\ \__\
##     \|_______|\|_______|\|_______|\|__| \|__|          \|_______|\|__|     \|_______|\|__|\|__|\|__|\|__|    \|__|  \|__|\|_______|\|__| \|__|
##  --
##  RPECK 23/04/2026 - Shopify Bulk Operations Migration
##  Defines the schema for Shopify Bulk Operations within XEngine.
################################################################
################################################################

# = Shopify Bulk Operations Database Provisioner
#
# Generates the data storage schema for registering and auditing high-volume 
# asynchronous GraphQL bulk data extractions running against Shopify's cloud cluster.
#
# == Database Resource Configuration
# * *Namespace:* +:shopify+
# * *Resource:* +:bulk_operation+
#
# == Schema Layout Matrix
# [shop_id]            The +uuid+ reference linking the operation to the requesting store.
# [shopify_id]         The unique canonical GraphQL global tracking ID string returned by Shopify.
# [status]             The execution tracking state token returned from the GraphQL endpoint.
# [error_code]         The numeric exception profile raised during engine runtime processing blocks.
# [file_size]          The capacity density of the compiled payload flat file evaluated in bytes.
# [download_url]       The temporary secured S3 bucket download link generated by Shopify.
# [root_object_count]  The number of top-level parents (e.g., Products) parsed out of the file.
# [object_count]       The grand total tally of all JSONL rows (parents and child edges combined).
# [query]              The original outbound GraphQL structural definition string passed to the API.
# [completed_at]       The timestamp indicating exactly when Shopify finished the extraction loop.
#
# == Index Profiles
# * A strict unique composite database index is placed on <tt>[:shop_id, :shopify_id]</tt> 
#   to guarantee multi-tenant execution isolation boundaries.
class CreateXEngineShopifyBulkOperations < XEngine::Core::Database::Migration

  # RPECK 23/04/2026 - Dynamically set resource for table naming logic
  set_resource :shopify, :bulk_operation

  # Executes schema generation transformations on the target database engine layer.
  #
  # @return [void]
  def up 
    create_table table_name, **table_options do |t|
      # Multi-tenant relation anchor point
      t.belongs_to :shop, type: :uuid, foreign_key: { to_table: shop_table, on_delete: :cascade }, null: false

      # Shopify Tracking Metadata
      t.string   :shopify_id,   null: false
      t.string   :status,       null: false, default: "CREATED"
      t.string   :error_code,   null: true # Changed to string in case Shopify uses alphanumeric codes later
      t.bigint   :file_size,    null: true
      t.text     :download_url, null: true
      
      # Extraction Analysis Properties
      t.integer  :root_object_count, null: true
      t.integer  :object_count,      null: true
      t.text     :query,             null: false

      t.timestamps 
      t.datetime :completed_at, null: true

      # Multi-column unique index protecting tenant data isolation boundaries
      t.index [:shop_id, :shopify_id], unique: true, name: 'idx_shopify_bulk_ops_on_shop_and_shopify_id'
    end
  end

  private

  # Resolves the fully namespaced physical table string value for the parent +Shop+ resource.
  #
  # @return [String]
  def shop_table
    XEngine::Core::Model.table_name_for(:shopify, :shop)
  end
  
end
# :startdoc: